/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.analizadorlexico.backend.frontend;

import com.mycompany.analizadorlexico.backend.EditorJsonFile;
import com.mycompany.analizadorlexico.backend.GestorArchivos;
import com.mycompany.analizadorlexico.backend.LectorDeArchivos;
import java.io.File;

/**
 *
 * @author edu
 */
public class EdicionJson extends javax.swing.JPanel {

    private  AnalizadorFrame panelPadre;
    private EditorJsonFile editorJson;
    private LectorDeArchivos lectorArchivos;
    private GestorArchivos gestorArchivos;
    /**
     * Creates new form EdicionJson
     */
    public EdicionJson(AnalizadorFrame padre, EditorJsonFile editorJson) {
        initComponents();
        //Frontend
        this.panelPadre = padre;
        
        //backend
        this.editorJson  = editorJson;
        this.gestorArchivos = editorJson.getGestorArchivos();
        this.lectorArchivos = new LectorDeArchivos();
        
        
        configurarPanel();
    }
    
    private void configurarPanel(){
        File file = gestorArchivos.getJsonConfigFile();
        String contenido = lectorArchivos.leerArchivoTexto(file);
        String nombreFile = file.getName();
        
        this.areadeTexto.setText(contenido);
        this.nombreLbl.setText("    Nombre json: "+ nombreFile);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        guardarBtn = new javax.swing.JButton();
        cancelarBtn = new javax.swing.JButton();
        nombreLbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        areadeTexto = new javax.swing.JTextArea();

        guardarBtn.setBackground(new java.awt.Color(102, 102, 102));
        guardarBtn.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        guardarBtn.setForeground(new java.awt.Color(153, 153, 255));
        guardarBtn.setText("Guardar");
        guardarBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        guardarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarBtnActionPerformed(evt);
            }
        });

        cancelarBtn.setBackground(new java.awt.Color(102, 102, 102));
        cancelarBtn.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        cancelarBtn.setForeground(new java.awt.Color(153, 153, 255));
        cancelarBtn.setText("Cancelar");
        cancelarBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cancelarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarBtnActionPerformed(evt);
            }
        });

        nombreLbl.setBackground(new java.awt.Color(204, 204, 255));
        nombreLbl.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        nombreLbl.setText("    Nombre json:");

        areadeTexto.setBackground(new java.awt.Color(204, 255, 255));
        areadeTexto.setColumns(20);
        areadeTexto.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        areadeTexto.setForeground(new java.awt.Color(0, 0, 0));
        areadeTexto.setRows(5);
        jScrollPane1.setViewportView(areadeTexto);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nombreLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(guardarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancelarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 697, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(guardarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addComponent(nombreLbl)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cancelarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarBtnActionPerformed
        this.panelPadre.volverAlPanelAnalizador();
    }//GEN-LAST:event_cancelarBtnActionPerformed

    private void guardarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarBtnActionPerformed
        this.editorJson.editarJson(areadeTexto.getText());
        this.panelPadre.recargarJsonFile(); // este método debería ir en otro lado
        this.panelPadre.volverAlPanelAnalizador();
    }//GEN-LAST:event_guardarBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areadeTexto;
    private javax.swing.JButton cancelarBtn;
    private javax.swing.JButton guardarBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nombreLbl;
    // End of variables declaration//GEN-END:variables
}
